version: '3.7'

services:
  postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_DB: "Board"
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes: 
          - pg-data:/var/lib/postgresql/data
        ports:
          - '5432:5432'
        networks:
          - 'bulletin-board-web-app'

volumes:
  pg-data:
  
networks:
  bulletin-board-web-app: